---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

    ## Database, choose either mysql or postgres, some subsequent roles will be configured
    ## depending on your choice here.
    - { role: mysql }

    ## Scripting / Language support
    - { role: php-apache }    # PHP using Apache and mod-php

    ## Install Compass in the box
    - { role: compass }

    ## Install Composer in the box
    - { role: composer }

    ## Install the ssh rule, installs gitlab.liip.ch and github.com host key
    - { role: ssh }

  # If needed, you can specify your own tasks, here is an example :
  tasks:
    - name: ensure php5-apcu and php5-xsl are installed
      apt: pkg={{ item }} state=present
      sudo: yes
      with_items:
        - php5-apcu
        - php5-xsl
      notify: restart apache

    - name: copy default config file
      shell: cp -n /vagrant/config/default_config.yml /vagrant/config/config.yml

    - name: create and adapt permissions on some directories
      file: path={{ item }} state=directory mode=o+rwx
      with_items :
        - /vagrant/files/user_image
        - /vagrant/files/track_thumbnails
        - /vagrant/files/track_files

    - name: install composer depedencies
      shell: cd /vagrant/; composer install

    - name: mysql reset database
      shell: cd /vagrant/; ./console mysql:reset